Create service order
techsweave/orders pull request #2
Opened 2021-05-31 09:36 UTC by Manuv46

2021-05-31 13:03 UTC, URBA22 requested changes

2021-05-31 13:03 UTC, URBA22 commented on src/functions/deleteOrder/handler.ts
> +            await deleteOrder(event.pathParameters.id),
This is very unsafe. 
This function allow every authenticated user to delete every order, with no check on userId.
It also allow the user to delete a 'completed' order, but a user can delete the order only if the order is not completed yet. If we don't check the status, we're going to lose the story of user's orders.
Important: a vendor can never be able to delete or modify an order, or he could scam customers! (For example he change the price in the order).
Same whit the update function.

2021-05-31 13:03 UTC, URBA22 commented on src/functions/getOrder/handler.ts
> +            await getOrder(event.pathParameters?.id),
You have to check if the order userId is the same as `await user.getUserId()` or a user could see a different user order (if he is not a vendor).

2021-05-31 13:03 UTC, URBA22 commented on src/functions/getOrder/function.ts
> +const getOrder = async (id: string): Promise<Order> => {
```suggestion
const getOrder = async (id: string, userId: string): Promise<Order> => {
```

2021-05-31 13:03 UTC, URBA22 commented on src/functions/scanOrder/function.ts
> +const scanOrder = async (filter: any): Promise<{
```suggestion
const scanOrder = async (filter: any, userId?: string): Promise<{
```

2021-05-31 13:03 UTC, URBA22 commented on src/functions/scanOrder/function.ts
> +    let lastKey: Partial<Order>;
```suggestion
    let lastKey: Partial<Order>;
    let filter = await objectToConditionExpression(filter.filter);
    if (userId) {
        filter = {
            type = 'And',
            conditions: [{
                    type = 'Equals',
                    subject = 'userId',
                    object = userId
                },
                filter 
            ]
    }
```
Maybe you have to switch subject and object, I don't remebember.

2021-05-31 13:03 UTC, URBA22 commented on src/functions/scanOrder/function.ts
>          filter: await objectToConditionExpression(filter.filter)
```suggestion
        filter: filter
```

2021-05-31 13:03 UTC, URBA22 commented on src/functions/scanOrder/handler.ts
> +        //const user: AuthenticatedUser = await AuthenticatedUser.fromToken(event.headers?.AccessToken);
```suggestion
        const user: AuthenticatedUser = await AuthenticatedUser.fromToken(event.headers?.AccessToken);
```

2021-05-31 13:03 UTC, URBA22 commented on src/functions/scanOrder/handler.ts
> +
```suggestion
let userId = null;
if (!(await user.isVendor()))
    userId = await userId.getUserId();
```

2021-05-31 13:03 UTC, URBA22 commented on src/functions/scanOrder/handler.ts
> +        const result = await scanOrder(event.body);
```suggestion
        const result = await scanOrder(event.body, userId);
```
Same logic of get:
- If user is customer: he can see only orders that belong to him
- If user is vendor: he can see all orders

I suggest some ideas about how implement this logic.

2021-06-01 07:16 UTC, URBA22 approved these changes

2021-06-01 08:41 UTC, samupd2013 approved these changes

2021-06-01 14:16 UTC, merged